package controller;

import entity.Product;
import entity.ProductDAO;
import java.io.IOException;
import jakarta.servlet.ServletException;
import java.sql.SQLException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;

@WebServlet("/admin/productActions")
public class ProductActionServlet extends HttpServlet {
    private ProductDAO productDAO;

    public void init() {
        productDAO = new ProductDAO();
    }

    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {

        String action = request.getParameter("action");

        try {
            switch (action) {
                case "create":
                    insertProduct(request, response);
                    break;
                case "update":
                    updateProduct(request, response);
                    break;
                case "delete":
                    deleteProduct(request, response);
                    break;
                default:
                    response.sendRedirect("products?action=LIST");
                    break;
            }
        } catch (SQLException ex) {
            throw new ServletException(ex);
        }
    }

    private void insertProduct(HttpServletRequest request, HttpServletResponse response)
            throws IOException, SQLException {
        // If Product_ID is auto-incrementing, you omit the ID field here.
        // Based on your Product.java constructor, ID is required. Assuming ID is auto-gen in DB.
        String name = request.getParameter("productName");
        String desc = request.getParameter("productDescription");
        String color = request.getParameter("productColor");
        String size = request.getParameter("productSize");
        String price = request.getParameter("productPrice");

        // Use the default constructor and setters since ID is auto-generated by DB
        Product newProduct = new Product();
        newProduct.setProductName(name);
        newProduct.setProductDescription(desc);
        newProduct.setProductColor(color);
        newProduct.setProductSize(size);
        newProduct.setProductPrice(price);

        productDAO.insert(newProduct);
        response.sendRedirect("products?action=LIST"); // Redirect back to the list view
    }

    private void updateProduct(HttpServletRequest request, HttpServletResponse response)
            throws IOException, SQLException {
        int id = Integer.parseInt(request.getParameter("id"));
        String name = request.getParameter("productName");
        String desc = request.getParameter("productDescription");
        String color = request.getParameter("productColor");
        String size = request.getParameter("productSize");
        String price = request.getParameter("productPrice");

        Product product = new Product(id, name, desc, color, size, price);
        productDAO.update(product);
        response.sendRedirect("products?action=LIST");
    }

    private void deleteProduct(HttpServletRequest request, HttpServletResponse response)
            throws IOException, SQLException {
        int id = Integer.parseInt(request.getParameter("id"));
        Product product = new Product(); // Only need the ID to delete
        product.setID(id);
        productDAO.delete(product);
        response.sendRedirect("products?action=LIST");
    }
}